"""Reusable Airflow notification callbacks."""

from __future__ import annotations

from html import escape
import logging
from typing import Any, Callable

from airflow.models import Variable
from airflow.utils.email import send_email

logger = logging.getLogger(__name__)


def _parse_recipients(value: str | None) -> list[str]:
    if not value:
        return []

    return [
        recipient.strip()
        for recipient in value.replace(";", ",").split(",")
        if recipient.strip()
    ]


def _get_failure_error(context: dict[str, Any], task_id: str) -> Any:
    error = context.get("failure_error") or context.get("error")
    if error:
        return error

    task_instance = context.get("task_instance") or context.get("ti")
    if task_instance is None:
        return None

    try:
        return task_instance.xcom_pull(task_ids=task_id, key="failure_error")
    except Exception:
        logger.exception("Failed to pull failure_error from XCom.")
        return None


def _html_cell(value: object) -> str:
    if value is None:
        return "N/A"
    return escape(str(value)).replace("\n", "<br>")


def _html_table(rows: list[tuple[str, object]]) -> str:
    body_rows = "".join(
        "<tr>"
        '<td style="width:180px;padding:10px 12px;border-bottom:1px solid #e2e8f0;'
        'background:#f8fafc;color:#475569;font-size:13px;font-weight:700;">'
        f"{_html_cell(label)}</td>"
        '<td style="padding:10px 12px;border-bottom:1px solid #e2e8f0;'
        'color:#0f172a;font-size:13px;">'
        f"{_html_cell(value)}</td>"
        "</tr>"
        for label, value in rows
    )
    return (
        '<table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;'
        'border-radius:8px;overflow:hidden;background:#ffffff;">'
        f"<tbody>{body_rows}</tbody>"
        "</table>"
    )


def _build_failure_email_html(
    *,
    dag_id: str,
    task_id: str,
    run_id: str,
    logical_date: object,
    failure_error: object,
) -> str:
    return (
        '<div style="font-family:Arial,Helvetica,sans-serif;line-height:1.45;'
        'color:#0f172a;background:#f8fafc;padding:24px;">'
        '<div style="max-width:860px;margin:0 auto;">'
        '<div style="background:#ffffff;border:1px solid #e2e8f0;border-radius:10px;'
        'padding:22px 24px;margin-bottom:16px;">'
        '<div style="font-size:13px;color:#64748b;margin-bottom:4px;">Airflow Alert</div>'
        '<h1 style="font-size:24px;line-height:1.25;margin:0;color:#0f172a;">'
        "Task Failed"
        "</h1>"
        '<div style="display:inline-block;margin-top:12px;padding:5px 10px;'
        'border-radius:999px;border:1px solid #fecaca;background:#fef2f2;'
        'color:#b91c1c;font-size:12px;font-weight:700;letter-spacing:0.3px;">'
        "FAILED</div>"
        "</div>"
        '<div style="background:#ffffff;border:1px solid #e2e8f0;border-radius:10px;'
        'padding:18px 20px;margin-bottom:16px;">'
        '<h2 style="font-size:16px;margin:0 0 12px;color:#0f172a;">Run Info</h2>'
        + _html_table(
            [
                ("DAG", dag_id),
                ("Task", task_id),
                ("Run ID", run_id),
                ("Logical Date", logical_date),
            ]
        )
        + "</div>"
        '<div style="background:#ffffff;border:1px solid #e2e8f0;border-radius:10px;'
        'padding:18px 20px;margin-bottom:16px;">'
        '<h2 style="font-size:16px;margin:0 0 12px;color:#991b1b;">Error</h2>'
        '<div style="border:1px solid #fecaca;border-radius:8px;background:#fef2f2;'
        'padding:14px 16px;color:#7f1d1d;font-size:13px;">'
        f"{_html_cell(failure_error)}"
        "</div>"
        "</div>"
        '<div style="font-size:12px;color:#64748b;margin-top:12px;">'
        "Generated by Airflow failure callback."
        "</div>"
        "</div></div>"
    )


def build_gmail_failure_callback(
    recipients_variable: str = "failure_email",
    default_recipients: str | None = "khoinm0603@gmail.com",
) -> Callable[[dict[str, Any]], None]:
    """Build an on_failure callback that sends email through Airflow SMTP/Gmail."""

    def _callback(context: dict[str, Any]) -> None:
        recipients = _parse_recipients(
            Variable.get(recipients_variable, default_var=default_recipients)
        )
        if not recipients:
            logger.warning(
                "Skip failure email because Airflow Variable '%s' is empty.",
                recipients_variable,
            )
            return

        dag = context.get("dag")
        dag_run = context.get("dag_run")
        task_instance = context.get("task_instance") or context.get("ti")
        exception = context.get("exception")

        dag_id = getattr(dag, "dag_id", None) or getattr(dag_run, "dag_id", "unknown")
        task_id = getattr(task_instance, "task_id", "dag")
        run_id = getattr(dag_run, "run_id", "unknown")
        logical_date = context.get("logical_date") or context.get("execution_date")
        failure_error = _get_failure_error(context, task_id) or exception

        subject = f"[Airflow][FAILED] {dag_id}.{task_id}"
        html_content = _build_failure_email_html(
            dag_id=str(dag_id),
            task_id=str(task_id),
            run_id=str(run_id),
            logical_date=logical_date,
            failure_error=failure_error,
        )

        send_email(
            to=recipients,
            subject=subject,
            html_content=html_content,
        )

    return _callback
